version: '3.8'
services:
  web_app:
    build: ./
    ports:
      - 3000:3000
    environment:
      DB_URL: mongodb://database/yelp-camp
  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - yelpcamp:/data/db
volumes:
  yelpcamp: